//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenBroadcaster.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenBroadcaster.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified broadcaster does not exist anymore..
        /// </summary>
        internal static string BcasterDoesNotExistMsg {
            get {
                return ResourceManager.GetString("BcasterDoesNotExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcaster ID error!.
        /// </summary>
        internal static string BcasterIdErrorCaption {
            get {
                return ResourceManager.GetString("BcasterIdErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify broadcaster ID..
        /// </summary>
        internal static string BcasterIdErrorMsg {
            get {
                return ResourceManager.GetString("BcasterIdErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcasting stop failed..
        /// </summary>
        internal static string BcastingStopFailedMsg {
            get {
                return ResourceManager.GetString("BcastingStopFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcasting has been successfully stopped..
        /// </summary>
        internal static string BcastingStopOkMsg {
            get {
                return ResourceManager.GetString("BcastingStopOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string ChatMsgFormat {
            get {
                return ResourceManager.GetString("ChatMsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution error!.
        /// </summary>
        internal static string CommandExecErrorCaption {
            get {
                return ResourceManager.GetString("CommandExecErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string DefaultUserName {
            get {
                return ResourceManager.GetString("DefaultUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server: Start server before connecting clients..
        /// </summary>
        internal static string HttpRequestExcMsg {
            get {
                return ResourceManager.GetString("HttpRequestExcMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed due to server connection issues..
        /// </summary>
        internal static string OperationFailedMsg {
            get {
                return ResourceManager.GetString("OperationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} ({1}) {2} your broadcast..
        /// </summary>
        internal static string ReceiverStateChangedMsgFormat {
            get {
                return ResourceManager.GetString("ReceiverStateChangedMsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving has been successfully stopped..
        /// </summary>
        internal static string ReceivingStopOkMsg {
            get {
                return ResourceManager.GetString("ReceivingStopOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection error!.
        /// </summary>
        internal static string ServerConnErrorCaption {
            get {
                return ResourceManager.GetString("ServerConnErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the command. Possibly, the server was stopped..
        /// </summary>
        internal static string ServerStoppedMsg {
            get {
                return ResourceManager.GetString("ServerStoppedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Broadcasting.
        /// </summary>
        internal static string StopBcastingCaption {
            get {
                return ResourceManager.GetString("StopBcastingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Receiving.
        /// </summary>
        internal static string StopReceivingCaption {
            get {
                return ResourceManager.GetString("StopReceivingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name error!.
        /// </summary>
        internal static string UserNameErrorCaption {
            get {
                return ResourceManager.GetString("UserNameErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify user name..
        /// </summary>
        internal static string UserNameErrorMsg {
            get {
                return ResourceManager.GetString("UserNameErrorMsg", resourceCulture);
            }
        }
    }
}
